from __future__ import annotations

import importlib.util
import tempfile
import unittest
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
HAKO_PY = REPO_ROOT / "tools" / "hako.py"
SPEC = importlib.util.spec_from_file_location("hako_tool", HAKO_PY)
assert SPEC is not None and SPEC.loader is not None
HAKO = importlib.util.module_from_spec(SPEC)
SPEC.loader.exec_module(HAKO)


class BuildManifestTests(unittest.TestCase):
    def load(self, text: str):
        with tempfile.TemporaryDirectory() as temp_dir:
            path = Path(temp_dir) / "manifest.yaml"
            path.write_text(text, encoding="utf-8")
            return HAKO.resolve_config(HAKO.load_simple_yaml(path))

    def test_repository_manifest_matches_native_compatibility_defaults(self):
        config = HAKO.resolve_config(
            HAKO.load_simple_yaml(REPO_ROOT / "hakoniwa-build.yaml")
        )
        expected = (REPO_ROOT / "cmake" / "hako_build_defaults.conf").read_text(
            encoding="utf-8"
        )
        self.assertEqual(
            HAKO.render_native_defaults(config).splitlines()[1:],
            expected.splitlines()[1:],
        )

    def test_alternate_manifest_maps_all_fields_to_native_keys(self):
        config = HAKO.resolve_config(
            HAKO.load_simple_yaml(
                REPO_ROOT / "tests" / "fixtures" / "alternate-build.yaml"
            )
        )
        self.assertEqual(
            HAKO.render_native_defaults(config),
            """# Generated by tools/hako.py from the selected user-facing build manifest.
HAKO_DATA_MAX_ASSET_NUM=24
HAKO_PDU_CHANNEL_MAX=4096
HAKO_RECV_EVENT_MAX=2048
HAKO_SERVICE_CLIENT_MAX=128
HAKO_SERVICE_MAX=512
HAKO_CLIENT_NAMELEN_MAX=48
HAKO_SERVICE_NAMELEN_MAX=96
""",
        )

    def test_missing_limit_is_rejected(self):
        with self.assertRaisesRegex(HAKO.ConfigError, "missing required key"):
            self.load(
                """version: 1
limits:
  asset_num: 16
"""
            )

    def test_unsupported_version_is_rejected(self):
        with self.assertRaisesRegex(HAKO.ConfigError, "version must be 1"):
            self.load(
                """version: 2
limits:
  asset_num: 16
  pdu_channel_max: 8192
  recv_event_max: 4096
  service_client_max: 256
  service_max: 1024
  client_name_len_max: 64
  service_name_len_max: 128
"""
            )

    def test_unknown_limit_is_rejected(self):
        with self.assertRaisesRegex(HAKO.ConfigError, "unknown key"):
            self.load(
                """version: 1
limits:
  asset_num: 16
  pdu_channel_max: 8192
  recv_event_max: 4096
  service_client_max: 256
  service_max: 1024
  client_name_len_max: 64
  service_name_len_max: 128
  extra: 1
"""
            )

    def test_non_positive_and_boolean_limits_are_rejected(self):
        for invalid in ("0", "-1", "true"):
            with self.subTest(invalid=invalid):
                with self.assertRaisesRegex(HAKO.ConfigError, "positive integer"):
                    self.load(
                        f"""version: 1
limits:
  asset_num: {invalid}
  pdu_channel_max: 8192
  recv_event_max: 4096
  service_client_max: 256
  service_max: 1024
  client_name_len_max: 64
  service_name_len_max: 128
"""
                    )

    def test_config_option_and_native_arguments_are_distinct(self):
        args = HAKO.create_parser().parse_args(
            ["build", "--config", "custom.yaml", "--", "-Clean"]
        )
        self.assertEqual(args.config, "custom.yaml")
        self.assertEqual(args.native_args, ["--", "-Clean"])


if __name__ == "__main__":
    unittest.main()
