from __future__ import annotations

import importlib.util
import json
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path
from unittest.mock import patch


REPO_ROOT = Path(__file__).resolve().parents[1]
HAKO_PY = REPO_ROOT / "tools" / "hako.py"
SPEC = importlib.util.spec_from_file_location("hako_tool", HAKO_PY)
assert SPEC is not None and SPEC.loader is not None
HAKO = importlib.util.module_from_spec(SPEC)
SPEC.loader.exec_module(HAKO)


class BuildManifestTests(unittest.TestCase):
    def load(self, text: str):
        with tempfile.TemporaryDirectory() as temp_dir:
            path = Path(temp_dir) / "manifest.yaml"
            path.write_text(text, encoding="utf-8")
            return HAKO.resolve_config(HAKO.load_simple_yaml(path))

    def test_repository_manifest_matches_native_compatibility_defaults(self):
        config = HAKO.resolve_config(
            HAKO.load_simple_yaml(REPO_ROOT / "hakoniwa-build.yaml")
        )
        expected = (REPO_ROOT / "cmake" / "hako_build_defaults.conf").read_text(
            encoding="utf-8"
        )
        self.assertEqual(
            HAKO.render_native_defaults(config).splitlines()[1:],
            expected.splitlines()[1:],
        )

    def test_alternate_manifest_maps_all_fields_to_native_keys(self):
        config = HAKO.resolve_config(
            HAKO.load_simple_yaml(
                REPO_ROOT / "tests" / "fixtures" / "alternate-build.yaml"
            )
        )
        self.assertEqual(
            HAKO.render_native_defaults(config),
            """# Generated by tools/hako.py from the selected user-facing build manifest.
HAKO_DATA_MAX_ASSET_NUM=24
HAKO_PDU_CHANNEL_MAX=4096
HAKO_RECV_EVENT_MAX=2048
HAKO_SERVICE_CLIENT_MAX=128
HAKO_SERVICE_MAX=512
HAKO_CLIENT_NAMELEN_MAX=48
HAKO_SERVICE_NAMELEN_MAX=96
""",
        )

    def test_missing_limit_is_rejected(self):
        with self.assertRaisesRegex(HAKO.ConfigError, "missing required key"):
            self.load(
                """version: 1
limits:
  asset_num: 16
"""
            )

    def test_unsupported_version_is_rejected(self):
        with self.assertRaisesRegex(HAKO.ConfigError, "version must be 1"):
            self.load(
                """version: 2
limits:
  asset_num: 16
  pdu_channel_max: 8192
  recv_event_max: 4096
  service_client_max: 256
  service_max: 1024
  client_name_len_max: 64
  service_name_len_max: 128
"""
            )

    def test_unknown_limit_is_rejected(self):
        with self.assertRaisesRegex(HAKO.ConfigError, "unknown key"):
            self.load(
                """version: 1
limits:
  asset_num: 16
  pdu_channel_max: 8192
  recv_event_max: 4096
  service_client_max: 256
  service_max: 1024
  client_name_len_max: 64
  service_name_len_max: 128
  extra: 1
"""
            )

    def test_non_positive_and_boolean_limits_are_rejected(self):
        for invalid in ("0", "-1", "true"):
            with self.subTest(invalid=invalid):
                with self.assertRaisesRegex(HAKO.ConfigError, "positive integer"):
                    self.load(
                        f"""version: 1
limits:
  asset_num: {invalid}
  pdu_channel_max: 8192
  recv_event_max: 4096
  service_client_max: 256
  service_max: 1024
  client_name_len_max: 64
  service_name_len_max: 128
"""
                    )

    def test_python_soabi_defaults_to_legacy_false(self):
        config = self.load(
            """version: 1
limits:
  asset_num: 16
  pdu_channel_max: 8192
  recv_event_max: 4096
  service_client_max: 256
  service_max: 1024
  client_name_len_max: 64
  service_name_len_max: 128
"""
        )
        self.assertFalse(config["python"]["soabi"])

    def test_python_soabi_accepts_explicit_boolean(self):
        config = self.load(
            """version: 1
limits:
  asset_num: 16
  pdu_channel_max: 8192
  recv_event_max: 4096
  service_client_max: 256
  service_max: 1024
  client_name_len_max: 64
  service_name_len_max: 128
python:
  soabi: true
"""
        )
        self.assertTrue(config["python"]["soabi"])

    def test_python_soabi_rejects_non_boolean_and_unknown_keys(self):
        base = """version: 1
limits:
  asset_num: 16
  pdu_channel_max: 8192
  recv_event_max: 4096
  service_client_max: 256
  service_max: 1024
  client_name_len_max: 64
  service_name_len_max: 128
python:
"""
        with self.assertRaisesRegex(HAKO.ConfigError, "must be a boolean"):
            self.load(base + "  soabi: yes\n")
        with self.assertRaisesRegex(HAKO.ConfigError, "unknown key"):
            self.load(base + "  soabi: false\n  extra: true\n")

    def test_resolved_manifest_records_python_build_contract(self):
        config = HAKO.resolve_config(
            HAKO.load_simple_yaml(REPO_ROOT / "hakoniwa-build.yaml")
        )
        config["python"]["soabi"] = True
        rendered = HAKO.render_resolved_manifest(
            Path("/repo/hakoniwa-build.yaml"),
            Path("/repo/.hako/hako_build_defaults.conf"),
            config,
            {
                "implementation": "CPython",
                "executable": "/venv/bin/python",
                "version": "3.12.10",
                "major": 3,
                "minor": 12,
                "abi": "cpython-312-darwin",
                "extension_suffix": ".cpython-312-darwin.so",
                "artifact_name": "hakopy.cpython-312-darwin.so",
            },
        )
        self.assertIn("  soabi: true", rendered)
        self.assertIn("    version: \"3.12.10\"", rendered)
        self.assertIn("    abi: \"cpython-312-darwin\"", rendered)
        self.assertIn(
            "    artifact_name: \"hakopy.cpython-312-darwin.so\"",
            rendered,
        )

    def test_python_abi_prefers_reported_soabi(self):
        self.assertEqual(
            HAKO._normalized_python_abi(
                "cpython-312-x86_64-linux-gnu",
                ".cpython-312-x86_64-linux-gnu.so",
            ),
            "cpython-312-x86_64-linux-gnu",
        )

    def test_python_abi_falls_back_to_windows_tagged_extension_suffix(self):
        self.assertEqual(
            HAKO._normalized_python_abi("", ".cp312-win_amd64.pyd"),
            "cp312-win_amd64",
        )

    def test_python_abi_does_not_accept_untagged_extension(self):
        self.assertEqual(HAKO._normalized_python_abi("", ".pyd"), "")
        self.assertEqual(HAKO._normalized_python_abi("", ".so"), "")

    def test_python_build_metadata_uses_windows_extension_suffix_fallback(self):
        probe = {
            "implementation": "CPython",
            "executable": sys.executable,
            "version": "3.12.10",
            "major": 3,
            "minor": 12,
            "abi": "",
            "extension_suffix": ".cp312-win_amd64.pyd",
        }
        completed = subprocess.CompletedProcess(
            [sys.executable], 0, stdout=json.dumps(probe), stderr=""
        )
        with patch.object(
            HAKO, "_cmake_cache_value", return_value=sys.executable
        ), patch.object(HAKO.subprocess, "run", return_value=completed):
            metadata = HAKO._python_build_metadata(Path("build"), True)
        self.assertEqual(metadata["abi"], "cp312-win_amd64")
        self.assertEqual(metadata["artifact_name"], "hakopy.cp312-win_amd64.pyd")

    def test_python_build_metadata_rejects_untagged_fallback(self):
        probe = {
            "implementation": "CPython",
            "executable": sys.executable,
            "version": "3.12.10",
            "major": 3,
            "minor": 12,
            "abi": "",
            "extension_suffix": ".pyd",
        }
        completed = subprocess.CompletedProcess(
            [sys.executable], 0, stdout=json.dumps(probe), stderr=""
        )
        with patch.object(
            HAKO, "_cmake_cache_value", return_value=sys.executable
        ), patch.object(HAKO.subprocess, "run", return_value=completed):
            with self.assertRaisesRegex(
                HAKO.HakoError, "ABI-tagged extension metadata is unavailable"
            ):
                HAKO._python_build_metadata(Path("build"), True)

    def test_config_option_and_native_arguments_are_distinct(self):
        args = HAKO.create_parser().parse_args(
            ["build", "--config", "custom.yaml", "--", "-Clean"]
        )
        self.assertEqual(args.config, "custom.yaml")
        self.assertEqual(args.native_args, ["--", "-Clean"])

    def test_install_requires_explicit_install_directory(self):
        with self.assertRaises(SystemExit):
            HAKO.create_parser().parse_args(["install"])

    def test_local_build_paths_are_separate_from_manifest(self):
        args = HAKO.create_parser().parse_args(
            [
                "build",
                "--config",
                "custom.yaml",
                "--build-dir",
                "build-local",
                "--install-dir",
                ".hako/install",
                "--python-install-dir",
                ".hako/install/share/hakoniwa/python",
                "--python-executable",
                "/opt/python3.12",
                "--core-mmap-dir",
                ".hako/runtime/mmap",
            ]
        )
        self.assertEqual(args.config, "custom.yaml")
        self.assertEqual(args.build_dir, "build-local")
        self.assertEqual(args.install_dir, ".hako/install")
        self.assertEqual(
            args.python_install_dir,
            ".hako/install/share/hakoniwa/python",
        )
        self.assertEqual(args.python_executable, "/opt/python3.12")
        self.assertEqual(args.core_mmap_dir, ".hako/runtime/mmap")

    def test_omitted_config_uses_repository_manifest(self):
        args = HAKO.create_parser().parse_args(["doctor"])
        self.assertIsNone(args.config)
        self.assertEqual(
            HAKO._manifest_path(args.config),
            REPO_ROOT / "hakoniwa-build.yaml",
        )

    def test_explicit_relative_config_uses_current_directory(self):
        with tempfile.TemporaryDirectory() as temp_dir:
            working_dir = Path(temp_dir)
            manifest = working_dir / "custom.yaml"
            manifest.write_text("version: 1\n", encoding="utf-8")
            original_dir = HAKO.Path.cwd()
            try:
                HAKO.os.chdir(working_dir)
                self.assertEqual(HAKO._manifest_path("custom.yaml"), manifest.resolve())
            finally:
                HAKO.os.chdir(original_dir)

    def test_core_artifacts_are_compact_install_surfaces(self):
        with tempfile.TemporaryDirectory() as temp_dir:
            prefix = Path(temp_dir)
            (prefix / "bin").mkdir()
            (prefix / "bin" / "hako-cmd").write_text("", encoding="utf-8")
            (prefix / "lib" / "cmake" / "hakoniwa-core").mkdir(parents=True)
            (prefix / "lib" / "libhako.a").write_text("", encoding="utf-8")
            generated = prefix / "include" / "hakoniwa" / "pdu"
            generated.mkdir(parents=True)
            for index in range(100):
                (generated / f"generated_{index}.hpp").write_text("", encoding="utf-8")

            artifacts = HAKO._core_artifacts(prefix)

            self.assertIn(
                (Path("include/hakoniwa"), "directory"),
                artifacts,
            )
            self.assertIn((Path("lib/libhako.a"), "library"), artifacts)
            self.assertNotIn(
                (Path("include/hakoniwa/pdu/generated_0.hpp"), "header"),
                artifacts,
            )
            self.assertLess(len(artifacts), 10)

    def test_receipt_architecture_uses_foundation_vocabulary(self):
        expected = {
            "x86_64": "x64",
            "AMD64": "x64",
            "aarch64": "arm64",
            "arm64": "arm64",
        }
        for machine, architecture in expected.items():
            with self.subTest(machine=machine):
                self.assertEqual(
                    HAKO._normalized_architecture(machine),
                    architecture,
                )


if __name__ == "__main__":
    unittest.main()
