
# サーバー側イベント
HAKO_SERVICE_SERVER_API_EVENT_NONE = 0           # No event
HAKO_SERVICE_SERVER_API_EVENT_REQUEST_IN = 1     # New request received
HAKO_SERVICE_SERVER_API_EVENT_CANCEL = 2         # Cancel request received

# サーバー状態
HAKO_SERVICE_SERVER_API_STATUS_IDLE = 0
HAKO_SERVICE_SERVER_API_STATUS_DOING = 1
HAKO_SERVICE_SERVER_API_STATUS_CANCELING = 2

# クライアント側イベント
HAKO_SERVICE_CLIENT_API_EVENT_NONE = 0
HAKO_SERVICE_CLIENT_API_RESPONSE_IN = 1
HAKO_SERVICE_CLIENT_API_REQUEST_TIMEOUT = 2
HAKO_SERVICE_CLIENT_API_REQUEST_CANCEL_DONE = 3

# クライアント状態
HAKO_SERVICE_CLIENT_API_STATE_IDLE = 0
HAKO_SERVICE_CLIENT_API_STATE_DOING = 1
HAKO_SERVICE_CLIENT_API_STATE_CANCELING = 2

# リザルトコード（共通）
HAKO_SERVICE_API_RESULT_CODE_OK = 0
HAKO_SERVICE_API_RESULT_CODE_ERROR = 1
HAKO_SERVICE_API_RESULT_CODE_CANCELED = 2
HAKO_SERVICE_API_RESULT_CODE_INVALID = 3
HAKO_SERVICE_API_RESULT_CODE_BUSY = 4

# ステータス（共通）
HAKO_SERVICE_API_STATUS_NONE = 0
HAKO_SERVICE_API_STATUS_DOING = 1
HAKO_SERVICE_API_STATUS_CANCELING = 2
HAKO_SERVICE_API_STATUS_DONE = 3
HAKO_SERVICE_API_STATUS_ERROR = 4
