# hako_config.py

HAKO_FIXED_STRLEN_MAX = 256
HAKO_DATA_MAX_ASSET_NUM = 4

HAKO_ASSET_TIMEOUT_USEC = 30 * 1000 * 1000

HAKO_SHARED_MEMORY_BASE_ID = 0x00FF
HAKO_SHARED_MEMORY_ID_0 = 0x0 + HAKO_SHARED_MEMORY_BASE_ID
HAKO_SHARED_MEMORY_ID_1 = 0x1 + HAKO_SHARED_MEMORY_BASE_ID
HAKO_SHARED_MEMORY_ID_2 = 0x2 + HAKO_SHARED_MEMORY_BASE_ID

HAKO_LOGGER_DIRPATH = "./log/"
HAKO_LOGGER_FILE_PREFIX = "hako-"
HAKO_LOGGER_FILE_EXTENSION = ".log"

HAKO_LOGGER_ENTRYSIZE = 256
HAKO_LOGGER_MAXSIZE = 1024 * 1024
HAKO_LOGGER_LOGNUM = HAKO_LOGGER_MAXSIZE // HAKO_LOGGER_ENTRYSIZE

HAKO_LOGGER_ROTNUM = 3

HAKO_PDU_CHANNEL_MAX = 256

HAKO_CONFIG_DEFAULT_PATH = "/etc/hakoniwa/cpp_core_config.json"
HAKO_CONFIG_MAX_SEM = 1024
