#pragma once

namespace hako::service {
    enum HakoServiceOperationCodeType {
        HAKO_SERVICE_OPERATION_CODE_REQUEST = 0,
        HAKO_SERVICE_OPERATION_CODE_CANCEL,
        HAKO_SERVICE_OPERATION_NUM
    };
    enum HakoServiceStatusType {
        HAKO_SERVICE_STATUS_NONE = 0,
        HAKO_SERVICE_STATUS_DOING,
        HAKO_SERVICE_STATUS_CANCELING,
        HAKO_SERVICE_STATUS_DONE,
        HAKO_SERVICE_STATUS_ERROR,
        HAKO_SERVICE_STATUS_NUM
    };
    enum HakoServiceResultCodeType {
        HAKO_SERVICE_RESULT_CODE_OK = 0,
        HAKO_SERVICE_RESULT_CODE_ERROR,
        HAKO_SERVICE_RESULT_CODE_TIMEOUT,
        HAKO_SERVICE_RESULT_CODE_CANCELED,
        HAKO_SERVICE_RESULT_CODE_INVALID,
        HAKO_SERVICE_RESULT_CODE_BUSY,
        HAKO_SERVICE_RESULT_CODE_NOT_FOUND,
        HAKO_SERVICE_RESULT_CODE_NOT_SUPPORTED,
        HAKO_SERVICE_RESULT_CODE_NOT_READY,
        HAKO_SERVICE_RESULT_CODE_NOT_AVAILABLE,
        HAKO_SERVICE_RESULT_CODE_NOT_IMPLEMENTED,
        HAKO_SERVICE_RESULT_CODE_NUM
    };
}