#pragma once

#ifndef HAKO_RECV_EVENT_MAX
#define HAKO_RECV_EVENT_MAX 8192
#endif
#define HAKO_CLIENT_NAMELEN_MAX 256
#define HAKO_SERVICE_NAMELEN_MAX 256
#ifndef HAKO_SERVICE_CLIENT_MAX
#define HAKO_SERVICE_CLIENT_MAX 512
#endif
#ifndef HAKO_SERVICE_MAX
#define HAKO_SERVICE_MAX 2048
#endif
